import {ArrowLeft, Eye, GripVertical, Image, Music, Plus, Save, Trash2, Upload, X} from 'lucide-react';
import {useEffect, useState} from 'react';
import {Link, useNavigate, useParams, useSearchParams} from 'react-router-dom';
import {Header} from '../components/Header';
import {id, shortCode, slugify} from '../lib/id';
import {attachMediaByOrder, importMediaFiles, type ImportedMedia} from '../lib/media';
import {parseQuestions} from '../lib/parser';
import {testService} from '../services/storage';
import type {Question, QuestionType, QuizTest} from '../types';

const labels:Record<QuestionType,string>={single:'Один ответ',multiple:'Несколько ответов',short:'Короткий ответ',matching:'Сопоставление',ordering:'Последовательность'};
const blank=(type:QuestionType):Question=>({id:id(),type,text:'',points:1,...(type==='single'||type==='multiple'?{options:[1,2,3].map(()=>({id:id(),text:'',isCorrect:false}))}:type==='short'?{acceptedAnswers:['']}:type==='matching'?{pairs:[{id:id(),left:'',right:''},{id:id(),left:'',right:''}]}:{items:['','']})});
const newTest=():QuizTest=>{const testId=id();return{id:testId,slug:shortCode(testId),title:'Новый музыкальный тест',subject:'Сольфеджио',grade:'',topic:'',description:'',instructions:'',status:'draft',questions:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}};

export function Editor(){
  const {id:routeId}=useParams(); const nav=useNavigate(); const [params]=useSearchParams();
  const existing=routeId&&routeId!=='new'?testService.get(routeId):undefined;
  const [test,setTest]=useState<QuizTest>(()=>existing??newTest());
  const [importOpen,setImportOpen]=useState(params.has('import')); const [raw,setRaw]=useState('');
  const [unrecognized,setUnrecognized]=useState<string[]>([]); const [media,setMedia]=useState<ImportedMedia[]>([]); const [mediaError,setMediaError]=useState(''); const [saved,setSaved]=useState(true);
  useEffect(()=>{if(!saved){const timer=setTimeout(()=>save(),900);return()=>clearTimeout(timer)}},[test,saved]);
  const change=(patch:Partial<QuizTest>)=>{setTest(t=>({...t,...patch}));setSaved(false)};
  const save=(publish=false)=>{const next={...test,slug:test.slug||slugify(test.title),status:publish?'published':test.status,updatedAt:new Date().toISOString()} as QuizTest;try{testService.save(next);setTest(next);setSaved(true);if(routeId==='new')nav(`/editor/${next.id}`,{replace:true})}catch{alert('Не удалось сохранить: медиафайлы слишком велики для локального хранилища. Уменьшите файлы.')}};
  const add=(type:QuestionType)=>change({questions:[...test.questions,blank(type)]});
  const addMedia=async(files:FileList|File[])=>{const result=await importMediaFiles(files);setMedia(m=>[...m,...result.imported]);setMediaError(result.rejected.length?`Не добавлены: ${result.rejected.join(', ')}`:'')};
  const pasteMedia=async(e:React.ClipboardEvent)=>{const files=Array.from(e.clipboardData.items).filter(x=>x.kind==='file').map(x=>x.getAsFile()).filter((x):x is File=>Boolean(x));if(files.length)await addMedia(files)};
  const importNow=()=>{const parsed=parseQuestions(raw);const questions=attachMediaByOrder(parsed.questions,media);change({questions:[...test.questions,...questions]});setUnrecognized(parsed.unrecognized);if(!parsed.unrecognized.length){setImportOpen(false);setRaw('');setMedia([])}};
  return <>
    <div className="editor-top"><Link to="/tests"><ArrowLeft/>Все тесты</Link><span className={saved?'saved':'unsaved'}>● {saved?'Сохранено':'Сохраняем…'}</span><button className="button" onClick={()=>setImportOpen(true)}><Upload/>Массовый импорт</button><button className="button" onClick={()=>save()}><Save/>Сохранить</button><button className="button primary" onClick={()=>save(true)}>Опубликовать</button></div>
    <Header eyebrow="Конструктор теста" title={test.title}/>
    <section className="editor-layout"><div>
      <article className="panel metadata"><input className="title-input" value={test.title} onChange={e=>change({title:e.target.value})}/><div className="form-grid"><label>Предмет<input value={test.subject} onChange={e=>change({subject:e.target.value})}/></label><label>Класс / группа<input value={test.grade} onChange={e=>change({grade:e.target.value})}/></label><label>Тема<input value={test.topic} onChange={e=>change({topic:e.target.value})}/></label><label>Описание<input value={test.description} onChange={e=>change({description:e.target.value})}/></label></div></article>
      {test.questions.map((q,i)=><QuestionCard key={q.id} q={q} index={i} update={value=>change({questions:test.questions.map((x,n)=>n===i?value:x)})} remove={()=>change({questions:test.questions.filter(x=>x.id!==q.id)})}/>)}
      {!test.questions.length&&<div className="empty panel"><Music/><h3>Добавьте первый вопрос</h3><p>Выберите тип справа или импортируйте текст вместе с медиафайлами.</p></div>}
    </div><aside className="tools panel"><h3>Добавить вопрос</h3>{(Object.keys(labels) as QuestionType[]).map(type=><button key={type} onClick={()=>add(type)}><Plus/>{labels[type]}</button>)}<hr/><button onClick={()=>setImportOpen(true)}><Upload/>Вставить весь тест</button>{test.status==='published'&&<Link className="button" to={`/test/${test.slug}`}><Eye/>Глазами ученика</Link>}</aside></section>
    {importOpen&&<div className="modal-back" onMouseDown={()=>setImportOpen(false)}><section className="modal" onMouseDown={e=>e.stopPropagation()} onPaste={pasteMedia}><p className="eyebrow">Текст + изображения + аудио</p><h2>Массовый импорт теста</h2><p>Вставьте текст и добавьте файлы. Первое изображение и первое аудио попадут в первый вопрос, вторые — во второй и так далее.</p><textarea rows={10} value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'1. Какой интервал содержит 5 ступеней?\n- Терция\n- Кварта\n- Квинта\nОтвет: Квинта'}/><label className="media-drop"><Upload/><b>Выбрать изображения и аудио</b><span>JPG, PNG, WEBP · MP3, WAV, M4A, OGG</span><input type="file" multiple accept="image/jpeg,image/png,image/webp,audio/mpeg,audio/wav,audio/mp4,audio/ogg,.m4a" onChange={e=>e.target.files&&addMedia(e.target.files)}/></label>{media.length>0&&<div className="media-import-list">{media.map((item,i)=><div key={item.id}>{item.kind==='image'?<img src={item.url} alt=""/>:<Music/>}<span><b>{i+1}. {item.name}</b><small>{item.kind==='image'?'Изображение':'Аудио'}</small></span><button onClick={()=>setMedia(m=>m.filter(x=>x.id!==item.id))}><X/></button></div>)}</div>}{mediaError&&<div className="warning">{mediaError}</div>}{unrecognized.length>0&&<div className="warning"><b>Не удалось распознать:</b><pre>{unrecognized.join('\n\n')}</pre></div>}<div className="actions"><button className="button" onClick={()=>setImportOpen(false)}>Отмена</button><button className="button primary" disabled={!raw.trim()} onClick={importNow}>Импортировать вопросы{media.length?` + ${media.length} файлов`:''}</button></div></section></div>}
  </>;
}

function QuestionCard({q,index,update,remove}:{q:Question;index:number;update:(q:Question)=>void;remove:()=>void}){
  const setFile=async(kind:'image'|'audio',files:FileList|null)=>{if(!files?.[0])return;const result=await importMediaFiles([files[0]]);const item=result.imported[0];if(!item){alert(`Неподдерживаемый или слишком большой файл: ${files[0].name}`);return}update(kind==='image'?{...q,imageUrl:item.url,imageName:item.name,imageAlt:q.imageAlt||item.name.replace(/\.[^.]+$/,'')}:{...q,audioUrl:item.url,audioName:item.name})};
  const setOptionCount=(count:number)=>{const options=q.options??[];update({...q,options:Array.from({length:Math.max(1,count)},(_,i)=>options[i]??{id:id(),text:'',isCorrect:false})})};
  const pasteOptions=(start:number,e:React.ClipboardEvent<HTMLInputElement>)=>{const lines=e.clipboardData.getData('text').split(/\r?\n/).map(line=>line.trim()).filter(Boolean);if(lines.length<2)return;e.preventDefault();const options=[...(q.options??[])];lines.forEach((text,offset)=>{const i=start+offset;options[i]=options[i]?{...options[i],text}:{id:id(),text,isCorrect:false}});update({...q,options})};
  return <article className="panel question"><div className="q-head"><span><GripVertical/>Вопрос {index+1}</span><select value={q.type} onChange={e=>update({...blank(e.target.value as QuestionType),text:q.text,points:q.points,imageUrl:q.imageUrl,imageName:q.imageName,imageAlt:q.imageAlt,audioUrl:q.audioUrl,audioName:q.audioName})}>{Object.entries(labels).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select><label>Баллы <input type="number" min="1" value={q.points} onChange={e=>update({...q,points:+e.target.value})}/></label><button className="danger" onClick={remove}><Trash2/></button></div><textarea rows={2} value={q.text} onChange={e=>update({...q,text:e.target.value})} placeholder="Текст вопроса"/>
    {(q.type==='single'||q.type==='multiple')&&<><div className="options-toolbar"><label>Количество вариантов<input type="number" min="1" value={q.options?.length??1} onChange={e=>setOptionCount(Number(e.target.value)||1)}/></label><span>Можно вставить список: один вариант на строку</span></div>{q.options?.map((option,i)=><div className="option" key={option.id}><input type={q.type==='single'?'radio':'checkbox'} name={q.id} checked={option.isCorrect} onChange={()=>update({...q,options:q.options!.map((x,n)=>({...x,isCorrect:q.type==='single'?n===i:n===i?!x.isCorrect:x.isCorrect}))})}/><input value={option.text} placeholder={`Вариант ${i+1}`} onPaste={e=>pasteOptions(i,e)} onChange={e=>update({...q,options:q.options!.map((x,n)=>n===i?{...x,text:e.target.value}:x)})}/><button className="remove-option danger" aria-label={`Удалить вариант ${i+1}`} title="Удалить вариант" disabled={q.options!.length<=1} onClick={()=>update({...q,options:q.options!.filter((_,n)=>n!==i)})}><X/></button></div>)}<button className="add-option" onClick={()=>setOptionCount((q.options?.length??0)+1)}><Plus/>Добавить вариант</button></>}
    {q.type==='short'&&<input value={q.acceptedAnswers?.join('; ')} onChange={e=>update({...q,acceptedAnswers:e.target.value.split(';')})} placeholder="Допустимые ответы через ;"/>}
    {q.type==='matching'&&q.pairs?.map((pair,i)=><div className="pair" key={pair.id}><input value={pair.left} onChange={e=>update({...q,pairs:q.pairs!.map((x,n)=>n===i?{...x,left:e.target.value}:x)})}/><span>↔</span><input value={pair.right} onChange={e=>update({...q,pairs:q.pairs!.map((x,n)=>n===i?{...x,right:e.target.value}:x)})}/></div>)}
    {q.type==='ordering'&&q.items?.map((value,i)=><div className="option" key={i}><b>{i+1}</b><input value={value} onChange={e=>update({...q,items:q.items!.map((x,n)=>n===i?e.target.value:x)})}/></div>)}
    {(q.imageUrl||q.audioUrl)&&<div className="media-preview">{q.imageUrl&&<div><img src={q.imageUrl} alt={q.imageAlt??''}/><label>Alt-текст<input value={q.imageAlt??''} onChange={e=>update({...q,imageAlt:e.target.value})}/></label><button className="danger" onClick={()=>update({...q,imageUrl:undefined,imageName:undefined,imageAlt:undefined})}><Trash2/>Удалить изображение</button></div>}{q.audioUrl&&<div><audio controls preload="metadata" src={q.audioUrl}/><span>{q.audioName}</span><button className="danger" onClick={()=>update({...q,audioUrl:undefined,audioName:undefined})}><Trash2/>Удалить аудио</button></div>}</div>}
    <div className="media-row"><label className="media-button"><Image/>{q.imageUrl?'Заменить изображение':'Изображение'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile('image',e.target.files)}/></label><label className="media-button"><Music/>{q.audioUrl?'Заменить аудио':'Аудио'}<input type="file" accept="audio/mpeg,audio/wav,audio/mp4,audio/ogg,.m4a" onChange={e=>setFile('audio',e.target.files)}/></label></div>
  </article>;
}
