import{ArrowLeft,ArrowRight,Check,ChevronDown,ChevronUp,Music2}from'lucide-react';import{useState}from'react';import{useParams}from'react-router-dom';import{scoreTest}from'../lib/scoring';import{resultService,telegramService,testService}from'../services/storage';import type{Answer,Attempt,Question,Student}from'../types';
export function StudentQuiz(){const{slug}=useParams();const test=testService.get(slug??'');const[student,setStudent]=useState<Student>({firstName:'',lastName:'',group:'',comment:''});const[started,setStarted]=useState(false);const[answers,setAnswers]=useState<Record<string,Answer>>({});const[result,setResult]=useState<Attempt>();if(!test||test.status!=='published')return <div className="student-shell"><div className="empty"><h2>Тест недоступен</h2><p>Ссылка неверна или тест ещё не опубликован.</p></div></div>;if(result)return <div className="student-shell"><div className="result-card"><span className="result-note">♪</span><p className="eyebrow">Тест завершён</p><h1>{student.firstName}, прекрасная работа!</h1><div className="result-ring"><strong>{result.percentage}%</strong><span>{result.score} из {result.maxScore} баллов</span></div><h2>Оценка: {result.grade}</h2><p>Результат сохранён и уже доступен преподавателю.</p></div></div>;if(!started)return <div className="student-shell"><div className="student-brand"><Music2/>NotaTest</div><article className="welcome-card"><p className="eyebrow">{test.subject} · {test.grade}</p><h1>{test.title}</h1><p>{test.description}</p><div className="quiz-meta"><span><b>{test.questions.length}</b> вопросов</span><span><b>{test.questions.reduce((n,q)=>n+q.points,0)}</b> баллов</span></div><h3>Представьтесь перед началом</h3><div className="form-grid"><label>Имя *<input required value={student.firstName} onChange={e=>setStudent({...student,firstName:e.target.value})}/></label><label>Фамилия *<input required value={student.lastName} onChange={e=>setStudent({...student,lastName:e.target.value})}/></label><label>Класс / группа<input value={student.group} onChange={e=>setStudent({...student,group:e.target.value})}/></label></div><button className="button primary wide" disabled={!student.firstName||!student.lastName} onClick={()=>setStarted(true)}>Начать тест <ArrowRight/></button></article></div>;const finish=async()=>{
  if(!confirm('Завершить и отправить ответы?'))return;

  const r=scoreTest(test,student,answers);

  try{
    const saved=await resultService.save(r);
    setResult(saved);
    void telegramService.notifyNewAttempt(saved,test);
  }catch(error){
    console.error('Ошибка сохранения результата',error);
    alert('Не удалось сохранить результат. Проверьте интернет и попробуйте ещё раз.');
  }
};return <div className="student-shell quiz-page"><div className="student-brand"><Music2/>NotaTest</div><header><div><p className="eyebrow">{test.subject}</p><h2>{test.title}</h2></div><div className="progress"><span>{Object.keys(answers).length} из {test.questions.length}</span><i style={{width:`${Object.keys(answers).length/test.questions.length*100}%`}}/></div></header>{test.questions.map((q,i)=><StudentQuestion key={q.id} q={q} index={i} value={answers[q.id]} set={v=>setAnswers({...answers,[q.id]:v})}/>)}<button className="button primary finish" onClick={finish}><Check/>Завершить тест</button></div>}
function StudentQuestion({q,index,value,set}:{q:Question;index:number;value:Answer|undefined;set:(a:Answer)=>void}){const move=(dir:number)=>{const a=[...((value as string[])??[...(q.items??[])].sort(()=>Math.random()-.5))];const i=Math.max(0,Math.min(a.length-1,(a as string[]).findIndex(Boolean)));if(i+dir>=0&&i+dir<a.length)[a[i],a[i+dir]]=[a[i+dir],a[i]];set(a)};return <article className="student-question"><div className="number">{index+1}</div><div><div className="question-title"><h3>{q.text}</h3><span>{q.points} {q.points===1?'балл':'балла'}</span></div>{q.imageUrl&&<img src={q.imageUrl} alt={q.imageAlt??''}/>} {q.audioUrl&&<audio controls preload="none" src={q.audioUrl}/>} {q.type==='single'&&q.options?.map(o=><label className="answer-option"><input type="radio" name={q.id} checked={value===o.id} onChange={()=>set(o.id)}/><span>{o.text}</span></label>)}{q.type==='multiple'&&q.options?.map(o=><label className="answer-option"><input type="checkbox" checked={(value as string[]|undefined)?.includes(o.id)??false} onChange={e=>set(e.target.checked?[...((value as string[])??[]),o.id]:((value as string[])??[]).filter(x=>x!==o.id))}/><span>{o.text}</span></label>)}{q.type==='short'&&<input className="short-answer" value={(value as string)??''} onChange={e=>set(e.target.value)} placeholder="Введите ответ…"/>}{q.type==='matching'&&q.pairs?.map(p=><label className="match"><span>{p.left}</span><select value={(value as Record<string,string>|undefined)?.[p.left]??''} onChange={e=>set({...((value as Record<string,string>)??{}),[p.left]:e.target.value})}><option value="">Выберите…</option>{q.pairs?.map(x=><option>{x.right}</option>)}</select></label>)}{q.type==='ordering'&&<div className="ordering">{((value as string[])??q.items??[]).map((x,i)=><div><b>{i+1}</b><span>{x}</span><button disabled={i===0} onClick={()=>{const a=[...((value as string[])??q.items??[])];[a[i],a[i-1]]=[a[i-1],a[i]];set(a)}}><ChevronUp/></button><button disabled={i===q.items!.length-1} onClick={()=>{const a=[...((value as string[])??q.items??[])];[a[i],a[i+1]]=[a[i+1],a[i]];set(a)}}><ChevronDown/></button></div>)}</div>}</div></article>}
